name: Test changes

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop
    types:
      - synchronize
      # TODO: perhaps, must add "opened"

jobs:
  build:
    name: Run build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm test

  lint:
    name: Check codestyle
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run lint
