name: Test changes

on:
  push:
    branches:
      - "*"

jobs:
  unit-tests:
    name: Run build
    runs-on: ubuntu-18.04
    steps:
      - run: npm ci
      - run: npm run build

    name: Run unit tests
    runs-on: ubuntu-18.04
    steps:
      - run: npm ci
      - run: npm test
